### ISSUE TITLE
Issue with TNHaplotyper2 VCF

### ISSUE THREAD

**Issue by sbgLuka** [Sentieon/sentieon-scripts#3]
Hi, I tried merge MNP script with TNHaplotyper2 VCFs, since it has PID and PGT fields, so I expected to work fine. However in VCFlib script there is an error when parse_field function tries to get type of String, because of an "OBAM" and "OBAMRC" fields so I have added in class VCF(sharder.Shardable):

`decoders = {'Integer': int, 'Float': float, 'String': str}
 encoders = {'Integer': str, 'Float': str, 'String': str}`

and everything worked fine. You can test these to check whether it will work with TNHaplotyper2 VCFs or not. 

Best regards,
Luka.

**Comment by sbgLuka** [comment]
Just one update, it seems that mentioned fields "OBAM" and "OBAMRC" which introduced strings in INFO fields are from GATK FilterByOrientationBias tool which was later used so, sorry for the confusion. However, I think adding type string to decoder/encoder would create more bulletproof tool in these cases. I managed to make the tool work with this change.  

Thanks and sorry for the confusion, 
Luka.

**Comment by DonFreed** [comment]
Hi Luka,

Thanks for letting us know about this problem. Which version of the software package are you using? Could you check to see if this error still occurs with the vcflib in the latest version of the Sentieon software package (202010)? Version 201911.01 has some updates to vcflib that should have addressed this issue.

-Don

**Comment by sbgLuka** [comment]
Hi Don, thanks for answering. I think my Sentieon version used was 201911. Indeed, I tried version 202010 and it worked fine. So I will close this issue now :)

Best,
Luka.
