### ISSUE TITLE
How can I get  ”PANEL_OF_NORMAL_TNHAPLOTYPER“ in TNseq/tumor_only.sh？

### ISSUE THREAD

**Issue by bigtaotao** [Sentieon/sentieon-scripts#4]
Hello, I want to use ”tumor_only.sh“ but I don’t know how to get ”PANEL_OF_NORMAL_TNHAPLOTYPER“, do I need to use GATK to get Pon first？

**Comment by DonFreed** [comment]
The Sentieon manual has some instructions on generating a PoN file with TNhaplotyper here, https://support.sentieon.com/versions/201808.03/manual/TNseq_usage/tnseq/#generating-a-panel-of-normal-vcf-file.

You should be able to generate the PoN file using the TNhaplotyper/bcftools flow outlined in the manual without running the GATK.

**Comment by bigtaotao** [comment]
Thank you and have a nice day ！
