### ISSUE TITLE
Is IndelRealigner needed when calling somatic mutations

### ISSUE THREAD

**Issue by ysbioinfo** [Sentieon/sentieon-scripts#7]
Hi,
Thanks for continuous efforts on updating Sentieon. I noted the example pipeline is kind of different from what I saw in the last year. If I remember correctly, previously, it is recommended to (1) realign the reads around indels (2) co-realignment of tumor and normal, and then run TNscope/TNhaplotyper/TNsnv. But now I see these steps are removed. My questions are:
1. Should I follow the up-to-date example script without indel realignment?
2. TNscope/TNhaplotyper/TNhaplotyper2/TNsnv, which one, from your experience, has the best performance and is recommended for mutation detection?
3. I see in the new example scripts, there are some filtering on mutations using BCFtools. Do I need to modify the parameters to make them suitable for different sequencing depth (My data is 30X WGS, tumor-normal paired)

Thanks in advance!

Best
Yang

**Comment by haodongchen** [comment]
Hi Yang,

1. Indel realignment is optional. For the sake of simplicity, we removed these steps from the example scripts.
2. We recommend TNscope and TNhaplotyper2. TNscope is more sensitive than the other callers but requires additional filters to remove false positives.
3. Yes, the filter should be modified accordingly. Also, you can try TNhaplotyper2 for the 30x WGS tumor-normal paired. 

Please feel free to contact support@sentieon.com if you need more help. 

Thanks,
Haodong

**Comment by ysbioinfo** [comment]
Hi Haodong,
Thanks for your reply! I'll take a try.

Best
Yang
